[package]
name = "{{project-name}}-infrastructure"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
{{project-name}}-domain = { path = "../{{project-name}}-domain" }
{{project-name}}-application = { path = "../{{project-name}}-application" }
serde = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true, optional = true }

[features]
default = ["postgres"]
postgres = ["dep:sqlx"]
